//
// Generated file, do not edit! Created by nedtool 4.6 from configNetwork.msg.
//

#ifndef _CONFIGNETWORK_M_H_
#define _CONFIGNETWORK_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>configNetwork.msg:16</tt> by nedtool.
 * <pre>
 * message ConfigNetwork
 * {
 *     int sourceID;
 *     int destinationID;
 * }
 * </pre>
 */
class ConfigNetwork : public ::cMessage
{
protected:
    int sourceID_var;
    int destinationID_var;
    std::string weights_var;

private:
    void copy(const ConfigNetwork& other);

protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConfigNetwork&);

public:
    ConfigNetwork(const char *name=NULL, int kind=0, int srcID=0, int destID=0, std::string weights="");
    ConfigNetwork(const ConfigNetwork& other);
    virtual ~ConfigNetwork();
    ConfigNetwork& operator=(const ConfigNetwork& other);
    virtual ConfigNetwork *dup() const {return new ConfigNetwork(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSourceID() const;
    virtual void setSourceID(int sourceID);
    virtual int getDestinationID() const;
    virtual void setDestinationID(int destinationID);
    virtual std::string getPathsWeight() const;
};

inline void doPacking(cCommBuffer *b, ConfigNetwork& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ConfigNetwork& obj) {obj.parsimUnpack(b);}


#endif // ifndef _CONFIGNETWORK_M_H_

