//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
// 

message ConfigNetwork {
    int sourceID;
	int destinationID;
		
	int n0g1Tn1g0 = 2;
	int n0g2Tn8g0 = 10;
	
	int n1g1Tn2g0 = 4;
	int n1g2Tn3g0 = 20;
	
	int n2g1Tn5g0 = 14;
	
	int n3g1Tn4g0 = 9;
	int n3g1Tn10g0 = 18; 
	
	int n4g1Tn5g1 = 7;
	int n4g2Tn6g0 = 24;
	
	int n5g2Tn7g0 = 13;
	int n5g3Tn12g0 = 1;
	
	int n6g1Tn8g1 = 490;
	
	int n7g1Tn9g1 = 3;
	
	int n8g2Tn9g0 = 15;
	
	int n9g2Tn11g0 = 30;
	int n9g3Tn13g0 = 29;
	
	int n10g1Tn13g1 = 8;
	
	int n11g1Tn12g1 = 6; 
	
	int n12g2Tn13g2 = 2; 
	
}
